export const  mapDocName= {
    'bo-luat-dan-su': 'Bộ luật dân sự',
    'bo-luat-hang-hai': 'Bộ luật hàng hải',
    'bo-luat-hinh-su': 'Bộ luật hình sự',
    'bo-luat-lao-dong': 'Bộ luật lao động',
    'bo-luat-to-tung-dan-su': 'Bộ luật tố tụng dân sự',
    'bo-luat-to-tung-hinh-su': 'Bộ luật tố tụng hình sự',
    'hien-phap': 'Hiến pháp',
    'luat-an-ninh-quoc-gia': 'Luật an ninh quốc gia',
    'luat-ban-hanh-van-ban-quy-pham-phap-luat': 'Luật ban hành văn bản quy phạm pháp luật',
    'luat-bao-chi': 'Luật báo chí',
    'luat-bao-hiem-xa-hoi': 'Luật bảo hiểm xã hội',
    'luat-bao-ve-cham-soc-va-giao-duc-tre-em': 'Luật bảo vệ chăm sóc và giáo dục trẻ em',
    'luat-bao-ve-moi-truong': 'Luật bảo vệ môi trường',
    'luat-bao-ve-suc-khoe-nhan-dan': 'Luật bảo vệ sức khỏe nhân dân',
    'luat-bao-ve-va-phat-trien-rung': 'Luật bảo vệ và phát triển rừng',
    'luat-bau-cu-dai-bieu-hdnd': 'Luật bầu cử đại biểu hđnd',
    'luat-bau-cu-dai-bieu-quoc-hoi': 'Luật bầu cử đại biểu quốc hội',
    'luat-bien-gioi-quoc-gia': 'Luật biên giới quốc gia',
    'luat-binh-dang-gioi': 'Luật bình đẳng giới',
    'luat-cac-cong-cu-chuyen-nhuong': 'Luật các công cụ chuyển nhưỡng',
    'luat-cac-to-chuc-tin-dung': 'Luật các tổ chức tín dụng',
    'luat-cai-cach-ruong-dat': 'Luật cải cách ruộng đất',
    'luat-canh-tranh': 'Luật cạnh tranh',
    'luat-chung-khoan': 'Luật chứng khoán',
    'luat-chuyen-giao-cong-nghe': 'Luật chuyển giao công nghệ',
    'luat-cong-an-nhan-dan': 'Luật công an nhân dân',
    'luat-cong-chung': 'Luật công chứng',
    'luat-cong-doan': 'Luật công đoàn',
    'luat-cong-nghe-thong-tin': 'Luật công nghệ thông tin',
    'luat-cong-ty': 'Luật công ty',
    'luat-cu-tru': 'Luật cư trú',
    'luat-dam-bao-quyen-tu-do-than-the-va-quyen-bat-kha-xam-pham-doi-voi-nha-o-do-vat-thu-tin-cua-nhan-dan': 'Luật đảm bảo quyền tự do thân thể và quyền bất khả xâm phạm đối với nhà ở, đồ vật thụ tín của nhân dân',
    'luat-dat-dai': 'Luật đất đai',
    'luat-dau-khi': 'Luật dầu khí',
    'luat-dau-thau': 'Luật đấu thầu',
    'luat-dau-tu': 'Luật đầu tư',
    'luat-dau-tu-nuoc-ngoai-tai-viet-nam': 'Luật đầu tư nước ngoài tại việt nam',
    'luat-day-nghe': 'Luật dạy nghề',
    'luat-de-dieu': 'Luật đê điều',
    'luat-dien-anh': 'Luật điện ảnh',
    'luat-dien-luc': 'Luật điện lực',
    'luat-di-san-van-hoa': 'Luật di sản văn hóa',
    'luat-doanh-nghiep': 'Luật doanh nghiệp',
    'luat-doanh-nghiep-nha-nuoc': 'Luật doanh nghiệp nhà nước',
    'luat-doanh-nghiep-tu-nhan': 'Luật doanh nghiệp tư nhân',
    'luat-du-lich': 'Luật du lịch',
    'luat-duoc': 'Luật được',
    'luat-duong-sat': 'Luật đường sắt',
    'luat-giao-dich-dien-tu': 'Luật giao dịch điện tử',
    'luat-giao-duc': 'Luật giáo dục',
    'luat-giao-thong-duong-bo': 'Luật giao thông đường bộ',
    'luat-giao-thong-duong-thuy-noi-dia': 'Luật giao thông đường thủy nội địa',
    'luat-hai-quan': 'Luật hải quan',
    'luat-hang-khong-dan-dung-viet-nam': 'Luật hàng không dân dụng việt nam',
    'luat-hien-ghep-lay-mo-bo-phan-co-the-nguoi-va-hien-lay-xac': 'Luật hiến gắn lấy mỡ, bộ phận cơ thể người và hiến lấy xác',
    'luat-hoat-dong-giam-sat-cua-quoc-hoi-va-hoi-dong-nhan-dan': 'Luật hoạt động giám sát của quốc hội và hội đồng nhân dân',
    'luat-hon-nhan-va-gia-dinh': 'Luật hôn nhân và gia đình',
    'luat-hop-tac-xa': 'Luật hợp tác xã',
    'luat-ke-toan': 'Luật kế toán',
    'luat-khieu-nai-to-cao': 'Luật khiếu nại tố cáo',
    'luat-khoa-hoc-va-cong-nghe': 'Luật khoa học và công nghệ',
    'luat-khoang-san': 'Luật khoáng sản',
    'luat-khuyen-khich-dau-tu-trong-nuoc': 'Luật khuyến khích đầu tư trong nước',
    'luat-kiem-toan-nha-nuoc': 'Luật kiểm toán nhà nước',
    'luat-kinh-doanh-bao-hiem': 'Luật kinh doanh bảo hiểm',
    'luat-kinh-doanh-bat-dong-san': 'Luật kinh doanh bất động sản',
    'luat-ky-ket-gia-nhap-va-thuc-hien-dieu-uoc-quoc-te': 'Luật ký kết gia nhập và thực hiện điều ước quốc tế',
    'luat-luat-su': 'Luật luật sư',
    'luat-mat-tran-to-quoc-viet-nam': 'Luật mặt trận tổ quốc việt nam',
    'luat-ngan-hang-nha-nuoc': 'Luật ngân hàng nhà nước',
    'luat-ngan-sach-nha-nuoc': 'Luật ngân sách nhà nước',
    'luat-nghia-vu-quan-su': 'Luật nghĩa vụ quân sự',
    'luat-nguoi-lao-dong-viet-nam-di-lam-o-nuoc-ngoai-theo-hop-dong': 'Luật người lao động việt nam đi làm ở nước ngoài theo hợp đồng',
    'luat-nha-o': 'Luật nhà ở',
    'luat-pha-san': 'Luật phá sản',
    'luat-pho-cap-giao-duc-tieu-hoc': 'Luật phó cấp giáo dục tiểu học',
    'luat-phong-chay-chua-chay': 'Luật phòng cháy chữa cháy',
    'luat-phong-chong-ma-tuy': 'Luật phòng chống ma túy',
    'luat-phong-chong-nhiem-virus-gay-ra-hoi-chung-suy-giam-mien-dich-mac-phai-o-nguoi-hiv-aids': 'Luật phòng chống nhiễm virus gây ra hội chứng suy giảm miễn dịch mắc phải ở người HIV/AIDS',
    'luat-phong-chong-tham-nhung': 'Luật phòng chống tham nhũng',
    'luat-quan-ly-thue': 'Luật quản lý thuế',
    'luat-quoc-phong': 'Luật quốc phòng',
    'luat-quoc-tich-viet-nam': 'Luật quốc tịch việt nam',
    'luat-quy-dinh-quyen-tu-do-hoi-hop': 'Luật quy định quyền tự do hội họp',
    'luat-so-huu-tri-tue': 'Luật sở hữu trí tuệ',
    'luat-sy-quan-quan-doi-nhan-dan-viet-nam': 'Luật sỹ quan quân đội nhân dân việt nam',
    'luat-tai-nguyen-nuoc': 'Luật tài nguyên nước',
    'luat-thanh-nien': 'Luật thanh niên',
    'luat-thanh-tra': 'Luật thanh tra',
    'luat-the-duc-the-thao': 'Luật thể dục thể thao',
    'luat-thi-dua-khen-thuong': 'Luật thi đua khen thưởng',
    'luat-thong-ke': 'Luật thống kê',
    'luat-thuc-hanh-tiet-kiem-chong-lang-phi': 'Luật thực hành tiết kiệm chống lãng phí',
    'luat-thue-chuyen-quyen-su-dung-dat': 'Luật thuế chuyển quyền sử dụng đất',
    'luat-thue-gia-tri-gia-tang': 'Luật thuế giá trị gia tăng',
    'luat-thue-su-dung-dat-nong-nghiep': 'Luật thuế sử dụng đất nông nghiệp',
    'luat-thue-thu-nhap-doanh-nghiep': 'Luật thuế thu nhập doanh nghiệp',
    'luat-thue-tieu-thu-dac-biet': 'Luật thuế tiêu thụ đặc biệt',
    'luat-thue-xuat-khau-thue-nhap-khau': 'Luật thuế xuất khẩu, thuế nhập khẩu',
    'luat-thuong-mai': 'Luật thương mại',
    'luat-thuy-san': 'Luật thủy sản',
    'luat-tieu-chuan-va-quy-chuan-ky-thuat': 'Luật tiêu chuẩn và quy chuẩn kỹ thuật',
    'luat-to-chuc-chinh-phu': 'Luật tổ chức chính phủ',
    'luat-to-chuc-hoi-dong-nhan-dan-va-uy-ban-nhan-dan': 'Luật tổ chức hội đồng nhân dân và uỷ ban nhân dân',
    'luat-to-chuc-quoc-hoi': 'Luật tổ chức quốc hội',
    'luat-to-chuc-toa-an-nhan-dan': 'Luật tổ chức tòa án nhân dân',
    'luat-to-chuc-vien-kiem-sat-nhan-dan': 'Luật tổ chức viên kiểm sát nhân dân',
    'luat-tro-giup-phap-ly': 'Luật trợ giúp pháp lý',
    'luat-xay-dung': 'Luật xây dựng',
    'luat-xuat-ban': 'Luật xuất bản'
}